# AA分账App - Store screenshot composer (re-runnable)
# Input : app/test/store_screenshots/*.png  (1080x1920, generated by store_screenshots_test.dart)
# Output: docs/store/screenshots/raw/       (original)
#         docs/store/screenshots/branded/   (branded frame: app name + tagline + washi tape)
# Usage: powershell -ExecutionPolicy Bypass -File scripts\compose-store-screenshots.ps1
$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$root = Split-Path -Parent $PSScriptRoot
$srcDir  = Join-Path $root "app\test\store_screenshots"
$rawDir  = Join-Path $root "docs\store\screenshots\raw"
$branded = Join-Path $root "docs\store\screenshots\branded"
$icon    = Join-Path $root "docs\store\icons\icon-96.png"
$fontDir = Join-Path $root "app\packages\aa_design\assets\fonts"
New-Item -ItemType Directory -Force -Path $rawDir | Out-Null
New-Item -ItemType Directory -Force -Path $branded | Out-Null

function C([string]$hex, [int]$a = 255) {
  return [System.Drawing.Color]::FromArgb($a, [Convert]::ToInt32($hex.Substring(0,2),16), [Convert]::ToInt32($hex.Substring(2,2),16), [Convert]::ToInt32($hex.Substring(4,2),16))
}
$paper   = C "FBF3E4"
$card    = C "FFFDF8"
$ink     = C "443A32"
$inkSoft = C "8A7A68"
$lemon   = C "FFD166"
$coral   = C "FF8C69"

$pfc = New-Object System.Drawing.Text.PrivateFontCollection
$pfc.AddFontFile((Join-Path $fontDir "ZCOOLKuaiLe-Regular.ttf"))
$fTitle  = New-Object System.Drawing.Font($pfc.Families[0], 84, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)
$fTag    = New-Object System.Drawing.Font($pfc.Families[0], 40, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)
$fCorner = New-Object System.Drawing.Font($pfc.Families[0], 26, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)

# rounded-rect path helper
function RR($x, $y, $w, $h, $r) {
  $p = New-Object System.Drawing.Drawing2D.GraphicsPath
  $d = $r * 2
  $p.AddArc($x, $y, $d, $d, 180, 90)
  $p.AddArc($x + $w - $d, $y, $d, $d, 270, 90)
  $p.AddArc($x + $w - $d, $y + $h - $d, $d, $d, 0, 90)
  $p.AddArc($x, $y + $h - $d, $d, $d, 90, 90)
  $p.CloseFigure()
  return $p
}

function Compose([string]$shot, [string]$outName) {
  $img = [System.Drawing.Image]::FromFile($shot)          # 1080x1920
  $bmp = New-Object System.Drawing.Bitmap 1080, 1920
  $g = [System.Drawing.Graphics]::FromImage($bmp)
  $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
  $g.Clear($paper)

  # header: icon + name + tagline
  $ic = [System.Drawing.Image]::FromFile($icon)
  $g.DrawImage($ic, 70, 64, 168, 168)
  $ic.Dispose()
  $sf = New-Object System.Drawing.StringFormat
  $sf.Alignment = [System.Drawing.StringAlignment]::Near
  $g.DrawString("AA分账", $fTitle, (New-Object System.Drawing.SolidBrush $ink), (New-Object System.Drawing.PointF (276, 84)), $sf)
  $g.DrawString("和朋友轻松AA分账", $fTag, (New-Object System.Drawing.SolidBrush $inkSoft), (New-Object System.Drawing.PointF (280, 190)), $sf)

  # card: shadow + paper + border
  $cardPath = RR 54 290 972 1560 28
  $shadow = New-Object System.Drawing.SolidBrush ([System.Drawing.Color]::FromArgb(40, 0, 0, 0))
  $g.FillPath($shadow, (RR 64 302 972 1560 28))
  $g.FillPath((New-Object System.Drawing.SolidBrush $card), $cardPath)
  $borderPen = New-Object System.Drawing.Pen $ink, 7
  $g.DrawPath($borderPen, $cardPath)

  # screenshot with rounded clip
  $old = $g.Clip
  $g.SetClip((RR 70 308 940 1524 16), [System.Drawing.Drawing2D.CombineMode]::Replace)
  $g.DrawImage($img, 70, 308, 940, 1524)
  $g.Clip = $old
  $img.Dispose()

  # washi tape corners (hand style)
  $tape = New-Object System.Drawing.SolidBrush ([System.Drawing.Color]::FromArgb(200, $lemon))
  $g.FillRectangle($tape, 30, 262, 160, 56)
  $g.FillRectangle($tape, 890, 1826, 160, 56)
  $g.Dispose()
  $bmp.Save((Join-Path $branded $outName), [System.Drawing.Imaging.ImageFormat]::Png)
  $bmp.Dispose()
}

Get-ChildItem (Join-Path $srcDir "*.png") | Sort-Object Name | ForEach-Object {
  Copy-Item $_.FullName (Join-Path $rawDir $_.Name) -Force
  Compose $_.FullName $_.Name
  Write-Host "composed $($_.Name)"
}
Write-Host "OK -> $rawDir / $branded"